<?php

namespace App\Console;

use App\Console\Commands\ClickCommand;
use App\Console\Commands\ViewCommand;
use App\Console\Commands\WeatherCurlCommand;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        ViewCommand::class,
        ClickCommand::class,
        WeatherCurlCommand::class
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        $schedule->command('redis:view:start')->hourly();

        $schedule->command('weather:get')->hourly();
    }

    protected function scheduleCache()
    {
        return parent::scheduleCache(); // TODO: Change the autogenerated stub
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}
